apply plugin: 'com.android.application'

buildscript {
    repositories {
        google()
        mavenCentral()
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:8.0.0'
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
        jcenter()
    }
}

android {
    compileSdkVersion 36
    targetSdkVersion 36
    minSdkVersion 21

    defaultConfig {
        targetSdkVersion 36
    }
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation 'com.opentok.android:opentok-android-sdk:2.27.0'
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'com.google.android.material:material:1.9.0'
}